<div class="page-head">
  <h3><?php echo $this->__('Your order has been received.')?></h3>
</div>
<p><strong><?php echo $this->__('Thank you for your purchase!')?></strong></p>
<p>
  <?php if ($this->canPrint()) :?>
  <?php echo $this->__('Your order # is: <a href="%s">%s</a>', $this->getViewOrderUrl(), $this->getOrderId()) ?>.<br/>
  <?php  else :?>
  <?php echo $this->__('Your order # is: %s', $this->getOrderId()) ?>.<br/>
  <?php endif;?>
  <?=$this->__('You will receive an order confirmation email with details of your order and a link to track its progress.')?>
  <?php if ($this->canPrint()) :?>
  <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
	<?php endif;?>
</p>

<?php echo $this->getPrePaidData()?>

<div class="button-set">
  <button  class="form-button" onclick="window.location='<?php echo $this->getUrl()?>'"><span><?php echo $this->__('Continue Shopping')?></span></button>
</div>
